# Generated by Django 2.2.4 on 2019-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('brief_content', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
